image: alexbirne/texlive2018

thesis:
    stage: build
    script: cd && pwd && make
    cache:
        untracked: true
    artifacts:
        paths:
            - thesis.pdf
    only:
        - master
